# Generated by Django 3.2 on 2021-04-12 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crud_op',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='pics')),
                ('technology', models.CharField(max_length=200)),
                ('domain', models.CharField(max_length=200)),
                ('project', models.TextField()),
                ('blogs', models.TextField()),
                ('score', models.IntegerField()),
                ('placed', models.BooleanField(default=False)),
            ],
        ),
    ]
