# Generated by Django 3.2 on 2021-04-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_alter_crud_op_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='pics')),
                ('technology', models.CharField(max_length=200)),
                ('domain', models.CharField(max_length=200)),
                ('project', models.TextField()),
                ('blogs', models.TextField()),
                ('score', models.IntegerField()),
                ('placed', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Crud_op',
        ),
    ]
