# Generated by Django 3.2 on 2021-04-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_auto_20210413_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp_details',
            name='image',
        ),
        migrations.AlterField(
            model_name='emp_details',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
