# Generated by Django 3.2 on 2021-04-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_auto_20210413_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_details',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
